# Generated by Django 2.2.1 on 2019-05-13 13:38

import acl.default_acl
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('acl', django_mysql.models.JSONField(default=acl.default_acl.row_acl)),
                ('is_active', models.BooleanField(default=True, verbose_name='删除标记')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('user_uuid', models.CharField(max_length=64, null=True, verbose_name='用户UUID')),
                ('name', models.CharField(max_length=50, verbose_name='分类')),
                ('desc', models.CharField(default='no desciption', max_length=50, verbose_name='描述')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('acl', django_mysql.models.JSONField(default=acl.default_acl.row_acl)),
                ('is_active', models.BooleanField(default=True, verbose_name='删除标记')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('from_user_uuid', models.UUIDField(verbose_name='收藏用户UUID')),
                ('to_user_uuid', models.UUIDField(verbose_name='被收藏文章作者UUID')),
                ('kind', models.CharField(max_length=50, verbose_name='类型(文章/wiki/FAQ...)')),
                ('target_uuid', models.UUIDField(verbose_name='被收藏内容的UUID')),
                ('fav_name', models.CharField(max_length=50, verbose_name='收藏夹名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('acl', django_mysql.models.JSONField(default=acl.default_acl.row_acl)),
                ('is_active', models.BooleanField(default=True, verbose_name='删除标记')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('target_uuid', models.UUIDField(verbose_name='被收藏内容的UUID')),
                ('goal', models.SmallIntegerField(verbose_name='评分')),
                ('from_user_uuid', models.UUIDField(verbose_name='点赞用户UUID')),
                ('to_user_uuid', models.UUIDField(verbose_name='被点赞用户UUID')),
                ('kind', models.CharField(max_length=50, verbose_name='类型(文章/评论...)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('acl', django_mysql.models.JSONField(default=acl.default_acl.row_acl)),
                ('is_active', models.BooleanField(default=True, verbose_name='删除标记')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('user_uuid', models.CharField(max_length=64, null=True, verbose_name='用户UUID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('desc', models.CharField(db_index=True, default='no desciption', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('acl', django_mysql.models.JSONField(default=acl.default_acl.row_acl)),
                ('is_active', models.BooleanField(default=True, verbose_name='删除标记')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='标题')),
                ('markdown', models.TextField(verbose_name='Markdown正文')),
                ('body', models.TextField(verbose_name='HTML正文')),
                ('kind', models.CharField(max_length=50, verbose_name='类型(文章/原创/笔记)')),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Category')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='article.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LikeFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('acl', django_mysql.models.JSONField(default=acl.default_acl.row_acl)),
                ('is_active', models.BooleanField(default=True, verbose_name='删除标记')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('desc', models.CharField(max_length=200, verbose_name='介绍')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('acl', django_mysql.models.JSONField(default=acl.default_acl.row_acl)),
                ('is_active', models.BooleanField(default=True, verbose_name='删除标记')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('body', models.TextField(verbose_name='评论内容')),
                ('markdown', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Comment', verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
