# Generated by Django 2.2.1 on 2019-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190513_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.CharField(db_index=True, default='暂无', max_length=200, verbose_name='描述'),
            preserve_default=False,
        ),
    ]
