# Generated by Django 2.2.1 on 2019-05-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_post_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否为私密文章'),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('草稿', '草稿'), ('已发布', '已发布'), ('已保存', '已保存')], db_index=True, default='草稿', max_length=50, verbose_name='类型(文章/原创/笔记)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('原创', '原创'), ('转载', '转载'), ('翻译', '翻译'), ('笔记', '笔记')], db_index=True, max_length=50, verbose_name='类型(文章/原创/笔记)'),
        ),
    ]
