# Generated by Django 2.2.1 on 2019-06-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190515_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='访问次数'),
        ),
    ]
